repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
