# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  ContributorLicenseAgreement:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_CLATOOL }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/splunk/cla-agreement/blob/main/CLA.md"
          branch: "main"
          allowlist: dependabot[bot]
          remote-organization-name: splunk
          remote-repository-name: cla-agreement
  CodeOfConduct:
    runs-on: ubuntu-latest
    steps:
      - name: "COC Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Code of Conduct and I hereby accept the Terms') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_CLATOOL }}
        with:
          path-to-signatures: "signatures/version1/coc.json"
          path-to-document: "https://github.com/splunk/cla-agreement/blob/main/CODE_OF_CONDUCT.md"
          branch: "main"
          allowlist: dependabot[bot]
          remote-organization-name: splunk
          remote-repository-name: cla-agreement
          custom-pr-sign-comment: "I have read the Code of Conduct and I hereby accept the Terms"
          create-file-commit-message: "For example: Creating file for storing COC Signatures"
          signed-commit-message: "$contributorName has signed the COC in #$pullRequestNo"
          custom-notsigned-prcomment: "All contributors have NOT signed the COC Document"
          custom-allsigned-prcomment: "****CLA Assistant Lite bot**** All contributors have signed the COC  ✍️ ✅"
